# Generated by Django 3.0.5 on 2020-05-19 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Кол-во метров')),
            ],
            options={
                'verbose_name': 'Дистанция',
                'verbose_name_plural': 'Дистанции',
            },
        ),
        migrations.CreateModel(
            name='SportResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('level', models.IntegerField(choices=[(0, 'Локальный'), (1, 'Областной'), (2, 'Всероссийский'), (3, 'Международный')], verbose_name='Уровень соревнований')),
                ('prize', models.IntegerField(choices=[(0, 'Другое'), (1, '1 место'), (2, '2 место'), (3, '3 место')], verbose_name='Место')),
                ('result', models.TimeField(verbose_name='Время')),
                ('distance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Distance', verbose_name='Дистанция')),
                ('sportsman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Sportsman', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Спортивный результат',
                'verbose_name_plural': 'Спортивные результаты',
            },
        ),
    ]
