# Generated by Django 3.0.4 on 2020-04-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsman',
            name='back_type',
        ),
        migrations.RemoveField(
            model_name='sportsman',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='sportsman',
            name='front_type',
        ),
        migrations.RemoveField(
            model_name='sportsman',
            name='height_father',
        ),
        migrations.RemoveField(
            model_name='sportsman',
            name='height_mother',
        ),
        migrations.RemoveField(
            model_name='sportsman',
            name='type_body_father',
        ),
        migrations.RemoveField(
            model_name='sportsman',
            name='type_body_mother',
        ),
        migrations.RemoveField(
            model_name='sportsman',
            name='weight_father',
        ),
        migrations.RemoveField(
            model_name='sportsman',
            name='weight_mother',
        ),
        migrations.CreateModel(
            name='Primary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата обследования')),
                ('stage', models.CharField(blank=True, choices=[(0, '1 этап'), (1, '2 этап'), (2, '3 этап')], max_length=15, null=True, verbose_name='Этап')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Вес тела (кг)')),
                ('length', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Длина тела(см)')),
                ('spit_leg_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина ног от вертела(см)')),
                ('foot_length', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Длина стопы (см)')),
                ('torso_length_7', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Длина туловища от 7-го шейного позвонка(см)')),
                ('arm_span', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размах рук(см)')),
                ('chest_girth_inspiration', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Обхват грудной клетки на вдохе(см)')),
                ('exhaling_chest', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Обхват грудной клетки на выдохе(см)')),
                ('excursion_difference', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Экскурсия(разница)')),
                ('spirometry', models.PositiveIntegerField(blank=True, null=True, verbose_name='Спирометрия(ЖЕЛ)мл')),
                ('breath_hold_stange', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Проба с задер.дых.на вдохе(проба Штанге)сек')),
                ('dynamometry', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Становая динамометрия')),
                ('dynamometry_right', models.PositiveIntegerField(blank=True, null=True, verbose_name='Динамометрия правой кисти(кг)')),
                ('dynamometry_left', models.PositiveIntegerField(blank=True, null=True, verbose_name='Динамометрия левой кисти(кг)')),
                ('fat_mass', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% жировой массы')),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% мышечной массы')),
                ('open_eyes', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Открытые глаза (фон)')),
                ('close_eyes', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Закрытые глаза')),
                ('target', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Мишень')),
                ('pwc_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='PWC Кг мм')),
                ('pwc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='PWC ЧСС')),
                ('pressure_up', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Артериальное давление(верхнее)')),
                ('pressure_down', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Артериальное давление(нижнее)')),
                ('oxygen', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Максимальное потребление кислорода')),
                ('diseases', models.CharField(blank=True, max_length=250, null=True, verbose_name='Перенесенные заболевания(травмы)')),
                ('type_body_father', models.CharField(blank=True, choices=[(0, 'Эктоморф'), (1, 'Эндоморф'), (2, 'Мезоморф')], max_length=10, null=True, verbose_name='Тип тела отца')),
                ('type_body_mother', models.CharField(blank=True, choices=[(0, 'Эктоморф'), (1, 'Эндоморф'), (2, 'Мезоморф')], max_length=10, null=True, verbose_name='Тип тела матери')),
                ('front_type', models.CharField(blank=True, choices=[(0, 'Уплощенная'), (1, 'Цилиндрическая'), (2, 'Коническая'), (3, 'Нормальная')], max_length=15, null=True, verbose_name='Форма грудной клетки')),
                ('back_type', models.CharField(blank=True, choices=[(0, 'Нормальная'), (1, 'Плоская'), (2, 'Плоско-выгнутая'), (3, 'Сутуловатость'), (4, 'Круглая'), (5, 'Кругло-вогнутая')], max_length=20, null=True, verbose_name='Форма спины')),
                ('past_diseases', models.CharField(blank=True, max_length=250, null=True, verbose_name='Перенесенные заболевания(травмы)')),
                ('height_father', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Рост отца')),
                ('weight_father', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Вес отца')),
                ('body_type_father', models.CharField(blank=True, choices=[(0, 'Эктоморф'), (1, 'Эндоморф'), (2, 'Мезоморф')], max_length=10, null=True, verbose_name='Тип тела отца')),
                ('height_mother', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Рост матери')),
                ('weight_mother', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Вес матери')),
                ('body_type_mother', models.CharField(blank=True, choices=[(0, 'Эктоморф'), (1, 'Эндоморф'), (2, 'Мезоморф')], max_length=10, null=True, verbose_name='Тип тела матери')),
                ('chest_shape', models.CharField(blank=True, choices=[(0, 'Уплощенная'), (1, 'Цилиндрическая'), (2, 'Коническая'), (3, 'Нормальная')], max_length=15, null=True, verbose_name='Форма грудной клетки')),
                ('back_shape', models.CharField(blank=True, choices=[(0, 'Нормальная'), (1, 'Плоская'), (2, 'Плоско-выгнутая'), (3, 'Сутуловатость'), (4, 'Круглая'), (5, 'Кругло-вогнутая')], max_length=20, null=True, verbose_name='Форма спины')),
                ('speed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Быстрота')),
                ('strength', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сила%')),
                ('stamina', models.PositiveIntegerField(blank=True, null=True, verbose_name='Выносливость%')),
                ('coordination', models.PositiveIntegerField(blank=True, null=True, verbose_name='Координация%')),
                ('nervous_system_potential', models.IntegerField(blank=True, choices=[(0, 'Слабая'), (1, 'Средне-слабая'), (2, 'Средняя'), (3, 'Средне-сильная'), (4, 'Сильная')], default='Средняя', null=True, verbose_name='Потенциал нервной системы')),
                ('run_30', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Бег 30м')),
                ('jump_place', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Прыжок в длину с места')),
                ('pull_ups', models.PositiveIntegerField(blank=True, null=True, verbose_name='Подтягивания на перекладине')),
                ('concept', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Концепт(техническая гребля)')),
                ('run_1500', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Бег 1500м')),
                ('concept_500', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Концепт 500м')),
                ('motivation', models.IntegerField(blank=True, choices=[(0, 'Низкая'), (1, 'Средняя'), (2, 'Высокая')], null=True, verbose_name='Мотивация к тренеровочному процессу')),
                ('willed_qualities', models.IntegerField(blank=True, choices=[(0, 'Не развитый'), (1, 'Низкий'), (2, 'Высокий')], null=True, verbose_name='Развитие волевых качеств')),
                ('sportsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Sportsman', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Первичное',
                'verbose_name_plural': 'Первичные',
                'ordering': ('date',),
            },
        ),
    ]
