# Generated by Django 3.0.5 on 2020-05-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_distance_sportresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='school_progress',
            field=models.IntegerField(blank=True, choices=[(0, 'Отлично'), (1, 'Хорошо'), (2, 'Удовлетворительно')], null=True, verbose_name='Успеваемость в школе'),
        ),
    ]
