# Generated by Django 3.0.5 on 2020-05-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20200520_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary',
            name='height_father',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Рост отца'),
        ),
    ]
