# Generated by Django 3.0.5 on 2020-05-29 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20200520_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='sportsman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='registry.Sportsman', verbose_name='Спортсмен'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Вес тела (кг)'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='sportsman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='registry.Sportsman', verbose_name='Спортсмен'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Вес тела (кг)'),
        ),
    ]
