# Generated by Django 3.0.5 on 2020-06-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_auto_20200613_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportresult',
            name='sportsman',
        ),
    ]
